/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PortalClientIdRouteImport } from './routes/portal.$clientId'
import { Route as DashboardTasksRouteImport } from './routes/dashboard.tasks'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProposalsRouteImport } from './routes/dashboard.proposals'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardPortalRouteImport } from './routes/dashboard.portal'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiReferralsRouteImport } from './routes/api/referrals'
import { Route as ApiProposalsRouteImport } from './routes/api/proposals'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiInvoicesRouteImport } from './routes/api/invoices'
import { Route as ApiClientsRouteImport } from './routes/api/clients'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks.stripe'
import { Route as ApiTasksReorderRouteImport } from './routes/api/tasks.reorder'
import { Route as ApiTasksIdRouteImport } from './routes/api/tasks.$id'
import { Route as ApiProposalsIdRouteImport } from './routes/api/proposals.$id'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects.$id'
import { Route as ApiPortalTokenRouteImport } from './routes/api/portal.$token'
import { Route as ApiOnboardingCountsRouteImport } from './routes/api/onboarding.counts'
import { Route as ApiInvoicesProcessRecurringRouteImport } from './routes/api/invoices.process-recurring'
import { Route as ApiInvoicesIdRouteImport } from './routes/api/invoices.$id'
import { Route as ApiEmailWelcomeRouteImport } from './routes/api/email.welcome'
import { Route as ApiDashboardStatsRouteImport } from './routes/api/dashboard.stats'
import { Route as ApiClientsIdRouteImport } from './routes/api/clients.$id'
import { Route as ApiBillingSubscriptionRouteImport } from './routes/api/billing.subscription'
import { Route as ApiBillingInvoicesRouteImport } from './routes/api/billing.invoices'
import { Route as ApiBillingCreatePortalRouteImport } from './routes/api/billing.create-portal'
import { Route as ApiBillingCreateCheckoutRouteImport } from './routes/api/billing.create-checkout'
import { Route as ApiAuthValidateSignupRouteImport } from './routes/api/auth.validate-signup'
import { Route as ApiAiInlineRouteImport } from './routes/api/ai.inline'
import { Route as ApiAiConversationsRouteImport } from './routes/api/ai.conversations'
import { Route as ApiAiChatRouteImport } from './routes/api/ai.chat'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin.users'
import { Route as ApiAdminPromoCodesRouteImport } from './routes/api/admin.promo-codes'
import { Route as ApiAdminLeadsRouteImport } from './routes/api/admin.leads'
import { Route as ApiAdminCampaignRouteImport } from './routes/api/admin.campaign'
import { Route as ApiProposalsIdSendRouteImport } from './routes/api/proposals.$id.send'
import { Route as ApiPortalTokenWhiteboardRouteImport } from './routes/api/portal.$token.whiteboard'
import { Route as ApiPortalTokenRevisionRouteImport } from './routes/api/portal.$token.revision'
import { Route as ApiPortalTokenPresenceRouteImport } from './routes/api/portal.$token.presence'
import { Route as ApiPortalTokenPayProofRouteImport } from './routes/api/portal.$token.pay-proof'
import { Route as ApiPortalTokenPayRouteImport } from './routes/api/portal.$token.pay'
import { Route as ApiPortalTokenMessageRouteImport } from './routes/api/portal.$token.message'
import { Route as ApiPortalTokenFileDeleteRouteImport } from './routes/api/portal.$token.file-delete'
import { Route as ApiPortalTokenFileRouteImport } from './routes/api/portal.$token.file'
import { Route as ApiPortalTokenConfirmRouteImport } from './routes/api/portal.$token.confirm'
import { Route as ApiPortalTokenApproveRouteImport } from './routes/api/portal.$token.approve'
import { Route as ApiInvoicesIdVerifyRouteImport } from './routes/api/invoices.$id.verify'
import { Route as ApiInvoicesIdSendRouteImport } from './routes/api/invoices.$id.send'
import { Route as ApiInvoicesIdPayRouteImport } from './routes/api/invoices.$id.pay'
import { Route as ApiClientsIdWhiteboardRouteImport } from './routes/api/clients.$id.whiteboard'
import { Route as ApiClientsIdTimelineRouteImport } from './routes/api/clients.$id.timeline'
import { Route as ApiClientsIdSendWelcomeRouteImport } from './routes/api/clients.$id.send-welcome'
import { Route as ApiClientsIdRegeneratePortalRouteImport } from './routes/api/clients.$id.regenerate-portal'
import { Route as ApiAuth2faVerifyRouteImport } from './routes/api/auth.2fa.verify'
import { Route as ApiAuth2faValidateRouteImport } from './routes/api/auth.2fa.validate'
import { Route as ApiAuth2faSetupRouteImport } from './routes/api/auth.2fa.setup'
import { Route as ApiAuth2faDisableRouteImport } from './routes/api/auth.2fa.disable'
import { Route as ApiAiConversationsIdRouteImport } from './routes/api/ai.conversations.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalClientIdRoute = PortalClientIdRouteImport.update({
  id: '/portal/$clientId',
  path: '/portal/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProposalsRoute = DashboardProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortalRoute = DashboardPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsRoute = ApiReferralsRouteImport.update({
  id: '/api/referrals',
  path: '/api/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProposalsRoute = ApiProposalsRouteImport.update({
  id: '/api/proposals',
  path: '/api/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesRoute = ApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsRoute = ApiClientsRouteImport.update({
  id: '/api/clients',
  path: '/api/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksReorderRoute = ApiTasksReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => ApiTasksRoute,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTasksRoute,
} as any)
const ApiProposalsIdRoute = ApiProposalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProposalsRoute,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiPortalTokenRoute = ApiPortalTokenRouteImport.update({
  id: '/api/portal/$token',
  path: '/api/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingCountsRoute = ApiOnboardingCountsRouteImport.update({
  id: '/api/onboarding/counts',
  path: '/api/onboarding/counts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesProcessRecurringRoute =
  ApiInvoicesProcessRecurringRouteImport.update({
    id: '/process-recurring',
    path: '/process-recurring',
    getParentRoute: () => ApiInvoicesRoute,
  } as any)
const ApiInvoicesIdRoute = ApiInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvoicesRoute,
} as any)
const ApiEmailWelcomeRoute = ApiEmailWelcomeRouteImport.update({
  id: '/api/email/welcome',
  path: '/api/email/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsIdRoute = ApiClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiClientsRoute,
} as any)
const ApiBillingSubscriptionRoute = ApiBillingSubscriptionRouteImport.update({
  id: '/api/billing/subscription',
  path: '/api/billing/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingInvoicesRoute = ApiBillingInvoicesRouteImport.update({
  id: '/api/billing/invoices',
  path: '/api/billing/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCreatePortalRoute = ApiBillingCreatePortalRouteImport.update({
  id: '/api/billing/create-portal',
  path: '/api/billing/create-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCreateCheckoutRoute =
  ApiBillingCreateCheckoutRouteImport.update({
    id: '/api/billing/create-checkout',
    path: '/api/billing/create-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthValidateSignupRoute = ApiAuthValidateSignupRouteImport.update({
  id: '/api/auth/validate-signup',
  path: '/api/auth/validate-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiInlineRoute = ApiAiInlineRouteImport.update({
  id: '/api/ai/inline',
  path: '/api/ai/inline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConversationsRoute = ApiAiConversationsRouteImport.update({
  id: '/api/ai/conversations',
  path: '/api/ai/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPromoCodesRoute = ApiAdminPromoCodesRouteImport.update({
  id: '/api/admin/promo-codes',
  path: '/api/admin/promo-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLeadsRoute = ApiAdminLeadsRouteImport.update({
  id: '/api/admin/leads',
  path: '/api/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCampaignRoute = ApiAdminCampaignRouteImport.update({
  id: '/api/admin/campaign',
  path: '/api/admin/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProposalsIdSendRoute = ApiProposalsIdSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => ApiProposalsIdRoute,
} as any)
const ApiPortalTokenWhiteboardRoute =
  ApiPortalTokenWhiteboardRouteImport.update({
    id: '/whiteboard',
    path: '/whiteboard',
    getParentRoute: () => ApiPortalTokenRoute,
  } as any)
const ApiPortalTokenRevisionRoute = ApiPortalTokenRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => ApiPortalTokenRoute,
} as any)
const ApiPortalTokenPresenceRoute = ApiPortalTokenPresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => ApiPortalTokenRoute,
} as any)
const ApiPortalTokenPayProofRoute = ApiPortalTokenPayProofRouteImport.update({
  id: '/pay-proof',
  path: '/pay-proof',
  getParentRoute: () => ApiPortalTokenRoute,
} as any)
const ApiPortalTokenPayRoute = ApiPortalTokenPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => ApiPortalTokenRoute,
} as any)
const ApiPortalTokenMessageRoute = ApiPortalTokenMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => ApiPortalTokenRoute,
} as any)
const ApiPortalTokenFileDeleteRoute =
  ApiPortalTokenFileDeleteRouteImport.update({
    id: '/file-delete',
    path: '/file-delete',
    getParentRoute: () => ApiPortalTokenRoute,
  } as any)
const ApiPortalTokenFileRoute = ApiPortalTokenFileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => ApiPortalTokenRoute,
} as any)
const ApiPortalTokenConfirmRoute = ApiPortalTokenConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => ApiPortalTokenRoute,
} as any)
const ApiPortalTokenApproveRoute = ApiPortalTokenApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => ApiPortalTokenRoute,
} as any)
const ApiInvoicesIdVerifyRoute = ApiInvoicesIdVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiInvoicesIdRoute,
} as any)
const ApiInvoicesIdSendRoute = ApiInvoicesIdSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => ApiInvoicesIdRoute,
} as any)
const ApiInvoicesIdPayRoute = ApiInvoicesIdPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => ApiInvoicesIdRoute,
} as any)
const ApiClientsIdWhiteboardRoute = ApiClientsIdWhiteboardRouteImport.update({
  id: '/whiteboard',
  path: '/whiteboard',
  getParentRoute: () => ApiClientsIdRoute,
} as any)
const ApiClientsIdTimelineRoute = ApiClientsIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ApiClientsIdRoute,
} as any)
const ApiClientsIdSendWelcomeRoute = ApiClientsIdSendWelcomeRouteImport.update({
  id: '/send-welcome',
  path: '/send-welcome',
  getParentRoute: () => ApiClientsIdRoute,
} as any)
const ApiClientsIdRegeneratePortalRoute =
  ApiClientsIdRegeneratePortalRouteImport.update({
    id: '/regenerate-portal',
    path: '/regenerate-portal',
    getParentRoute: () => ApiClientsIdRoute,
  } as any)
const ApiAuth2faVerifyRoute = ApiAuth2faVerifyRouteImport.update({
  id: '/api/auth/2fa/verify',
  path: '/api/auth/2fa/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuth2faValidateRoute = ApiAuth2faValidateRouteImport.update({
  id: '/api/auth/2fa/validate',
  path: '/api/auth/2fa/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuth2faSetupRoute = ApiAuth2faSetupRouteImport.update({
  id: '/api/auth/2fa/setup',
  path: '/api/auth/2fa/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuth2faDisableRoute = ApiAuth2faDisableRouteImport.update({
  id: '/api/auth/2fa/disable',
  path: '/api/auth/2fa/disable',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConversationsIdRoute = ApiAiConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAiConversationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/leads': typeof ApiLeadsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/proposals': typeof ApiProposalsRouteWithChildren
  '/api/referrals': typeof ApiReferralsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/portal': typeof DashboardPortalRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/portal/$clientId': typeof PortalClientIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/campaign': typeof ApiAdminCampaignRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/admin/promo-codes': typeof ApiAdminPromoCodesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/conversations': typeof ApiAiConversationsRouteWithChildren
  '/api/ai/inline': typeof ApiAiInlineRoute
  '/api/auth/validate-signup': typeof ApiAuthValidateSignupRoute
  '/api/billing/create-checkout': typeof ApiBillingCreateCheckoutRoute
  '/api/billing/create-portal': typeof ApiBillingCreatePortalRoute
  '/api/billing/invoices': typeof ApiBillingInvoicesRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRoute
  '/api/clients/$id': typeof ApiClientsIdRouteWithChildren
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/email/welcome': typeof ApiEmailWelcomeRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRouteWithChildren
  '/api/invoices/process-recurring': typeof ApiInvoicesProcessRecurringRoute
  '/api/onboarding/counts': typeof ApiOnboardingCountsRoute
  '/api/portal/$token': typeof ApiPortalTokenRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/proposals/$id': typeof ApiProposalsIdRouteWithChildren
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/tasks/reorder': typeof ApiTasksReorderRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/ai/conversations/$id': typeof ApiAiConversationsIdRoute
  '/api/auth/2fa/disable': typeof ApiAuth2faDisableRoute
  '/api/auth/2fa/setup': typeof ApiAuth2faSetupRoute
  '/api/auth/2fa/validate': typeof ApiAuth2faValidateRoute
  '/api/auth/2fa/verify': typeof ApiAuth2faVerifyRoute
  '/api/clients/$id/regenerate-portal': typeof ApiClientsIdRegeneratePortalRoute
  '/api/clients/$id/send-welcome': typeof ApiClientsIdSendWelcomeRoute
  '/api/clients/$id/timeline': typeof ApiClientsIdTimelineRoute
  '/api/clients/$id/whiteboard': typeof ApiClientsIdWhiteboardRoute
  '/api/invoices/$id/pay': typeof ApiInvoicesIdPayRoute
  '/api/invoices/$id/send': typeof ApiInvoicesIdSendRoute
  '/api/invoices/$id/verify': typeof ApiInvoicesIdVerifyRoute
  '/api/portal/$token/approve': typeof ApiPortalTokenApproveRoute
  '/api/portal/$token/confirm': typeof ApiPortalTokenConfirmRoute
  '/api/portal/$token/file': typeof ApiPortalTokenFileRoute
  '/api/portal/$token/file-delete': typeof ApiPortalTokenFileDeleteRoute
  '/api/portal/$token/message': typeof ApiPortalTokenMessageRoute
  '/api/portal/$token/pay': typeof ApiPortalTokenPayRoute
  '/api/portal/$token/pay-proof': typeof ApiPortalTokenPayProofRoute
  '/api/portal/$token/presence': typeof ApiPortalTokenPresenceRoute
  '/api/portal/$token/revision': typeof ApiPortalTokenRevisionRoute
  '/api/portal/$token/whiteboard': typeof ApiPortalTokenWhiteboardRoute
  '/api/proposals/$id/send': typeof ApiProposalsIdSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/leads': typeof ApiLeadsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/proposals': typeof ApiProposalsRouteWithChildren
  '/api/referrals': typeof ApiReferralsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/portal': typeof DashboardPortalRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/portal/$clientId': typeof PortalClientIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/admin/campaign': typeof ApiAdminCampaignRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/admin/promo-codes': typeof ApiAdminPromoCodesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/conversations': typeof ApiAiConversationsRouteWithChildren
  '/api/ai/inline': typeof ApiAiInlineRoute
  '/api/auth/validate-signup': typeof ApiAuthValidateSignupRoute
  '/api/billing/create-checkout': typeof ApiBillingCreateCheckoutRoute
  '/api/billing/create-portal': typeof ApiBillingCreatePortalRoute
  '/api/billing/invoices': typeof ApiBillingInvoicesRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRoute
  '/api/clients/$id': typeof ApiClientsIdRouteWithChildren
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/email/welcome': typeof ApiEmailWelcomeRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRouteWithChildren
  '/api/invoices/process-recurring': typeof ApiInvoicesProcessRecurringRoute
  '/api/onboarding/counts': typeof ApiOnboardingCountsRoute
  '/api/portal/$token': typeof ApiPortalTokenRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/proposals/$id': typeof ApiProposalsIdRouteWithChildren
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/tasks/reorder': typeof ApiTasksReorderRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/ai/conversations/$id': typeof ApiAiConversationsIdRoute
  '/api/auth/2fa/disable': typeof ApiAuth2faDisableRoute
  '/api/auth/2fa/setup': typeof ApiAuth2faSetupRoute
  '/api/auth/2fa/validate': typeof ApiAuth2faValidateRoute
  '/api/auth/2fa/verify': typeof ApiAuth2faVerifyRoute
  '/api/clients/$id/regenerate-portal': typeof ApiClientsIdRegeneratePortalRoute
  '/api/clients/$id/send-welcome': typeof ApiClientsIdSendWelcomeRoute
  '/api/clients/$id/timeline': typeof ApiClientsIdTimelineRoute
  '/api/clients/$id/whiteboard': typeof ApiClientsIdWhiteboardRoute
  '/api/invoices/$id/pay': typeof ApiInvoicesIdPayRoute
  '/api/invoices/$id/send': typeof ApiInvoicesIdSendRoute
  '/api/invoices/$id/verify': typeof ApiInvoicesIdVerifyRoute
  '/api/portal/$token/approve': typeof ApiPortalTokenApproveRoute
  '/api/portal/$token/confirm': typeof ApiPortalTokenConfirmRoute
  '/api/portal/$token/file': typeof ApiPortalTokenFileRoute
  '/api/portal/$token/file-delete': typeof ApiPortalTokenFileDeleteRoute
  '/api/portal/$token/message': typeof ApiPortalTokenMessageRoute
  '/api/portal/$token/pay': typeof ApiPortalTokenPayRoute
  '/api/portal/$token/pay-proof': typeof ApiPortalTokenPayProofRoute
  '/api/portal/$token/presence': typeof ApiPortalTokenPresenceRoute
  '/api/portal/$token/revision': typeof ApiPortalTokenRevisionRoute
  '/api/portal/$token/whiteboard': typeof ApiPortalTokenWhiteboardRoute
  '/api/proposals/$id/send': typeof ApiProposalsIdSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/leads': typeof ApiLeadsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/proposals': typeof ApiProposalsRouteWithChildren
  '/api/referrals': typeof ApiReferralsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/portal': typeof DashboardPortalRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/portal/$clientId': typeof PortalClientIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/campaign': typeof ApiAdminCampaignRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/admin/promo-codes': typeof ApiAdminPromoCodesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/conversations': typeof ApiAiConversationsRouteWithChildren
  '/api/ai/inline': typeof ApiAiInlineRoute
  '/api/auth/validate-signup': typeof ApiAuthValidateSignupRoute
  '/api/billing/create-checkout': typeof ApiBillingCreateCheckoutRoute
  '/api/billing/create-portal': typeof ApiBillingCreatePortalRoute
  '/api/billing/invoices': typeof ApiBillingInvoicesRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRoute
  '/api/clients/$id': typeof ApiClientsIdRouteWithChildren
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/email/welcome': typeof ApiEmailWelcomeRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRouteWithChildren
  '/api/invoices/process-recurring': typeof ApiInvoicesProcessRecurringRoute
  '/api/onboarding/counts': typeof ApiOnboardingCountsRoute
  '/api/portal/$token': typeof ApiPortalTokenRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/proposals/$id': typeof ApiProposalsIdRouteWithChildren
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/tasks/reorder': typeof ApiTasksReorderRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/ai/conversations/$id': typeof ApiAiConversationsIdRoute
  '/api/auth/2fa/disable': typeof ApiAuth2faDisableRoute
  '/api/auth/2fa/setup': typeof ApiAuth2faSetupRoute
  '/api/auth/2fa/validate': typeof ApiAuth2faValidateRoute
  '/api/auth/2fa/verify': typeof ApiAuth2faVerifyRoute
  '/api/clients/$id/regenerate-portal': typeof ApiClientsIdRegeneratePortalRoute
  '/api/clients/$id/send-welcome': typeof ApiClientsIdSendWelcomeRoute
  '/api/clients/$id/timeline': typeof ApiClientsIdTimelineRoute
  '/api/clients/$id/whiteboard': typeof ApiClientsIdWhiteboardRoute
  '/api/invoices/$id/pay': typeof ApiInvoicesIdPayRoute
  '/api/invoices/$id/send': typeof ApiInvoicesIdSendRoute
  '/api/invoices/$id/verify': typeof ApiInvoicesIdVerifyRoute
  '/api/portal/$token/approve': typeof ApiPortalTokenApproveRoute
  '/api/portal/$token/confirm': typeof ApiPortalTokenConfirmRoute
  '/api/portal/$token/file': typeof ApiPortalTokenFileRoute
  '/api/portal/$token/file-delete': typeof ApiPortalTokenFileDeleteRoute
  '/api/portal/$token/message': typeof ApiPortalTokenMessageRoute
  '/api/portal/$token/pay': typeof ApiPortalTokenPayRoute
  '/api/portal/$token/pay-proof': typeof ApiPortalTokenPayProofRoute
  '/api/portal/$token/presence': typeof ApiPortalTokenPresenceRoute
  '/api/portal/$token/revision': typeof ApiPortalTokenRevisionRoute
  '/api/portal/$token/whiteboard': typeof ApiPortalTokenWhiteboardRoute
  '/api/proposals/$id/send': typeof ApiProposalsIdSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/cookie'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/roadmap'
    | '/security'
    | '/signup'
    | '/terms'
    | '/api/clients'
    | '/api/invoices'
    | '/api/leads'
    | '/api/notifications'
    | '/api/ping'
    | '/api/profile'
    | '/api/projects'
    | '/api/proposals'
    | '/api/referrals'
    | '/api/tasks'
    | '/dashboard/ai'
    | '/dashboard/clients'
    | '/dashboard/invoices'
    | '/dashboard/portal'
    | '/dashboard/projects'
    | '/dashboard/proposals'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/portal/$clientId'
    | '/dashboard/'
    | '/api/admin/campaign'
    | '/api/admin/leads'
    | '/api/admin/promo-codes'
    | '/api/admin/users'
    | '/api/ai/chat'
    | '/api/ai/conversations'
    | '/api/ai/inline'
    | '/api/auth/validate-signup'
    | '/api/billing/create-checkout'
    | '/api/billing/create-portal'
    | '/api/billing/invoices'
    | '/api/billing/subscription'
    | '/api/clients/$id'
    | '/api/dashboard/stats'
    | '/api/email/welcome'
    | '/api/invoices/$id'
    | '/api/invoices/process-recurring'
    | '/api/onboarding/counts'
    | '/api/portal/$token'
    | '/api/projects/$id'
    | '/api/proposals/$id'
    | '/api/tasks/$id'
    | '/api/tasks/reorder'
    | '/api/webhooks/stripe'
    | '/api/ai/conversations/$id'
    | '/api/auth/2fa/disable'
    | '/api/auth/2fa/setup'
    | '/api/auth/2fa/validate'
    | '/api/auth/2fa/verify'
    | '/api/clients/$id/regenerate-portal'
    | '/api/clients/$id/send-welcome'
    | '/api/clients/$id/timeline'
    | '/api/clients/$id/whiteboard'
    | '/api/invoices/$id/pay'
    | '/api/invoices/$id/send'
    | '/api/invoices/$id/verify'
    | '/api/portal/$token/approve'
    | '/api/portal/$token/confirm'
    | '/api/portal/$token/file'
    | '/api/portal/$token/file-delete'
    | '/api/portal/$token/message'
    | '/api/portal/$token/pay'
    | '/api/portal/$token/pay-proof'
    | '/api/portal/$token/presence'
    | '/api/portal/$token/revision'
    | '/api/portal/$token/whiteboard'
    | '/api/proposals/$id/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/cookie'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/roadmap'
    | '/security'
    | '/signup'
    | '/terms'
    | '/api/clients'
    | '/api/invoices'
    | '/api/leads'
    | '/api/notifications'
    | '/api/ping'
    | '/api/profile'
    | '/api/projects'
    | '/api/proposals'
    | '/api/referrals'
    | '/api/tasks'
    | '/dashboard/ai'
    | '/dashboard/clients'
    | '/dashboard/invoices'
    | '/dashboard/portal'
    | '/dashboard/projects'
    | '/dashboard/proposals'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/portal/$clientId'
    | '/dashboard'
    | '/api/admin/campaign'
    | '/api/admin/leads'
    | '/api/admin/promo-codes'
    | '/api/admin/users'
    | '/api/ai/chat'
    | '/api/ai/conversations'
    | '/api/ai/inline'
    | '/api/auth/validate-signup'
    | '/api/billing/create-checkout'
    | '/api/billing/create-portal'
    | '/api/billing/invoices'
    | '/api/billing/subscription'
    | '/api/clients/$id'
    | '/api/dashboard/stats'
    | '/api/email/welcome'
    | '/api/invoices/$id'
    | '/api/invoices/process-recurring'
    | '/api/onboarding/counts'
    | '/api/portal/$token'
    | '/api/projects/$id'
    | '/api/proposals/$id'
    | '/api/tasks/$id'
    | '/api/tasks/reorder'
    | '/api/webhooks/stripe'
    | '/api/ai/conversations/$id'
    | '/api/auth/2fa/disable'
    | '/api/auth/2fa/setup'
    | '/api/auth/2fa/validate'
    | '/api/auth/2fa/verify'
    | '/api/clients/$id/regenerate-portal'
    | '/api/clients/$id/send-welcome'
    | '/api/clients/$id/timeline'
    | '/api/clients/$id/whiteboard'
    | '/api/invoices/$id/pay'
    | '/api/invoices/$id/send'
    | '/api/invoices/$id/verify'
    | '/api/portal/$token/approve'
    | '/api/portal/$token/confirm'
    | '/api/portal/$token/file'
    | '/api/portal/$token/file-delete'
    | '/api/portal/$token/message'
    | '/api/portal/$token/pay'
    | '/api/portal/$token/pay-proof'
    | '/api/portal/$token/presence'
    | '/api/portal/$token/revision'
    | '/api/portal/$token/whiteboard'
    | '/api/proposals/$id/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/cookie'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/roadmap'
    | '/security'
    | '/signup'
    | '/terms'
    | '/api/clients'
    | '/api/invoices'
    | '/api/leads'
    | '/api/notifications'
    | '/api/ping'
    | '/api/profile'
    | '/api/projects'
    | '/api/proposals'
    | '/api/referrals'
    | '/api/tasks'
    | '/dashboard/ai'
    | '/dashboard/clients'
    | '/dashboard/invoices'
    | '/dashboard/portal'
    | '/dashboard/projects'
    | '/dashboard/proposals'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/portal/$clientId'
    | '/dashboard/'
    | '/api/admin/campaign'
    | '/api/admin/leads'
    | '/api/admin/promo-codes'
    | '/api/admin/users'
    | '/api/ai/chat'
    | '/api/ai/conversations'
    | '/api/ai/inline'
    | '/api/auth/validate-signup'
    | '/api/billing/create-checkout'
    | '/api/billing/create-portal'
    | '/api/billing/invoices'
    | '/api/billing/subscription'
    | '/api/clients/$id'
    | '/api/dashboard/stats'
    | '/api/email/welcome'
    | '/api/invoices/$id'
    | '/api/invoices/process-recurring'
    | '/api/onboarding/counts'
    | '/api/portal/$token'
    | '/api/projects/$id'
    | '/api/proposals/$id'
    | '/api/tasks/$id'
    | '/api/tasks/reorder'
    | '/api/webhooks/stripe'
    | '/api/ai/conversations/$id'
    | '/api/auth/2fa/disable'
    | '/api/auth/2fa/setup'
    | '/api/auth/2fa/validate'
    | '/api/auth/2fa/verify'
    | '/api/clients/$id/regenerate-portal'
    | '/api/clients/$id/send-welcome'
    | '/api/clients/$id/timeline'
    | '/api/clients/$id/whiteboard'
    | '/api/invoices/$id/pay'
    | '/api/invoices/$id/send'
    | '/api/invoices/$id/verify'
    | '/api/portal/$token/approve'
    | '/api/portal/$token/confirm'
    | '/api/portal/$token/file'
    | '/api/portal/$token/file-delete'
    | '/api/portal/$token/message'
    | '/api/portal/$token/pay'
    | '/api/portal/$token/pay-proof'
    | '/api/portal/$token/presence'
    | '/api/portal/$token/revision'
    | '/api/portal/$token/whiteboard'
    | '/api/proposals/$id/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  CookieRoute: typeof CookieRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RoadmapRoute: typeof RoadmapRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiClientsRoute: typeof ApiClientsRouteWithChildren
  ApiInvoicesRoute: typeof ApiInvoicesRouteWithChildren
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiProposalsRoute: typeof ApiProposalsRouteWithChildren
  ApiReferralsRoute: typeof ApiReferralsRoute
  ApiTasksRoute: typeof ApiTasksRouteWithChildren
  PortalClientIdRoute: typeof PortalClientIdRoute
  ApiAdminCampaignRoute: typeof ApiAdminCampaignRoute
  ApiAdminLeadsRoute: typeof ApiAdminLeadsRoute
  ApiAdminPromoCodesRoute: typeof ApiAdminPromoCodesRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiConversationsRoute: typeof ApiAiConversationsRouteWithChildren
  ApiAiInlineRoute: typeof ApiAiInlineRoute
  ApiAuthValidateSignupRoute: typeof ApiAuthValidateSignupRoute
  ApiBillingCreateCheckoutRoute: typeof ApiBillingCreateCheckoutRoute
  ApiBillingCreatePortalRoute: typeof ApiBillingCreatePortalRoute
  ApiBillingInvoicesRoute: typeof ApiBillingInvoicesRoute
  ApiBillingSubscriptionRoute: typeof ApiBillingSubscriptionRoute
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiEmailWelcomeRoute: typeof ApiEmailWelcomeRoute
  ApiOnboardingCountsRoute: typeof ApiOnboardingCountsRoute
  ApiPortalTokenRoute: typeof ApiPortalTokenRouteWithChildren
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiAuth2faDisableRoute: typeof ApiAuth2faDisableRoute
  ApiAuth2faSetupRoute: typeof ApiAuth2faSetupRoute
  ApiAuth2faValidateRoute: typeof ApiAuth2faValidateRoute
  ApiAuth2faVerifyRoute: typeof ApiAuth2faVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/portal/$clientId': {
      id: '/portal/$clientId'
      path: '/portal/$clientId'
      fullPath: '/portal/$clientId'
      preLoaderRoute: typeof PortalClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/proposals': {
      id: '/dashboard/proposals'
      path: '/proposals'
      fullPath: '/dashboard/proposals'
      preLoaderRoute: typeof DashboardProposalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portal': {
      id: '/dashboard/portal'
      path: '/portal'
      fullPath: '/dashboard/portal'
      preLoaderRoute: typeof DashboardPortalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals': {
      id: '/api/referrals'
      path: '/api/referrals'
      fullPath: '/api/referrals'
      preLoaderRoute: typeof ApiReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proposals': {
      id: '/api/proposals'
      path: '/api/proposals'
      fullPath: '/api/proposals'
      preLoaderRoute: typeof ApiProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices': {
      id: '/api/invoices'
      path: '/api/invoices'
      fullPath: '/api/invoices'
      preLoaderRoute: typeof ApiInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients': {
      id: '/api/clients'
      path: '/api/clients'
      fullPath: '/api/clients'
      preLoaderRoute: typeof ApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/reorder': {
      id: '/api/tasks/reorder'
      path: '/reorder'
      fullPath: '/api/tasks/reorder'
      preLoaderRoute: typeof ApiTasksReorderRouteImport
      parentRoute: typeof ApiTasksRoute
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof ApiTasksRoute
    }
    '/api/proposals/$id': {
      id: '/api/proposals/$id'
      path: '/$id'
      fullPath: '/api/proposals/$id'
      preLoaderRoute: typeof ApiProposalsIdRouteImport
      parentRoute: typeof ApiProposalsRoute
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/portal/$token': {
      id: '/api/portal/$token'
      path: '/api/portal/$token'
      fullPath: '/api/portal/$token'
      preLoaderRoute: typeof ApiPortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/counts': {
      id: '/api/onboarding/counts'
      path: '/api/onboarding/counts'
      fullPath: '/api/onboarding/counts'
      preLoaderRoute: typeof ApiOnboardingCountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices/process-recurring': {
      id: '/api/invoices/process-recurring'
      path: '/process-recurring'
      fullPath: '/api/invoices/process-recurring'
      preLoaderRoute: typeof ApiInvoicesProcessRecurringRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/invoices/$id': {
      id: '/api/invoices/$id'
      path: '/$id'
      fullPath: '/api/invoices/$id'
      preLoaderRoute: typeof ApiInvoicesIdRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/email/welcome': {
      id: '/api/email/welcome'
      path: '/api/email/welcome'
      fullPath: '/api/email/welcome'
      preLoaderRoute: typeof ApiEmailWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/$id': {
      id: '/api/clients/$id'
      path: '/$id'
      fullPath: '/api/clients/$id'
      preLoaderRoute: typeof ApiClientsIdRouteImport
      parentRoute: typeof ApiClientsRoute
    }
    '/api/billing/subscription': {
      id: '/api/billing/subscription'
      path: '/api/billing/subscription'
      fullPath: '/api/billing/subscription'
      preLoaderRoute: typeof ApiBillingSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/invoices': {
      id: '/api/billing/invoices'
      path: '/api/billing/invoices'
      fullPath: '/api/billing/invoices'
      preLoaderRoute: typeof ApiBillingInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/create-portal': {
      id: '/api/billing/create-portal'
      path: '/api/billing/create-portal'
      fullPath: '/api/billing/create-portal'
      preLoaderRoute: typeof ApiBillingCreatePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/create-checkout': {
      id: '/api/billing/create-checkout'
      path: '/api/billing/create-checkout'
      fullPath: '/api/billing/create-checkout'
      preLoaderRoute: typeof ApiBillingCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/validate-signup': {
      id: '/api/auth/validate-signup'
      path: '/api/auth/validate-signup'
      fullPath: '/api/auth/validate-signup'
      preLoaderRoute: typeof ApiAuthValidateSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/inline': {
      id: '/api/ai/inline'
      path: '/api/ai/inline'
      fullPath: '/api/ai/inline'
      preLoaderRoute: typeof ApiAiInlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/conversations': {
      id: '/api/ai/conversations'
      path: '/api/ai/conversations'
      fullPath: '/api/ai/conversations'
      preLoaderRoute: typeof ApiAiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/promo-codes': {
      id: '/api/admin/promo-codes'
      path: '/api/admin/promo-codes'
      fullPath: '/api/admin/promo-codes'
      preLoaderRoute: typeof ApiAdminPromoCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/leads': {
      id: '/api/admin/leads'
      path: '/api/admin/leads'
      fullPath: '/api/admin/leads'
      preLoaderRoute: typeof ApiAdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/campaign': {
      id: '/api/admin/campaign'
      path: '/api/admin/campaign'
      fullPath: '/api/admin/campaign'
      preLoaderRoute: typeof ApiAdminCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proposals/$id/send': {
      id: '/api/proposals/$id/send'
      path: '/send'
      fullPath: '/api/proposals/$id/send'
      preLoaderRoute: typeof ApiProposalsIdSendRouteImport
      parentRoute: typeof ApiProposalsIdRoute
    }
    '/api/portal/$token/whiteboard': {
      id: '/api/portal/$token/whiteboard'
      path: '/whiteboard'
      fullPath: '/api/portal/$token/whiteboard'
      preLoaderRoute: typeof ApiPortalTokenWhiteboardRouteImport
      parentRoute: typeof ApiPortalTokenRoute
    }
    '/api/portal/$token/revision': {
      id: '/api/portal/$token/revision'
      path: '/revision'
      fullPath: '/api/portal/$token/revision'
      preLoaderRoute: typeof ApiPortalTokenRevisionRouteImport
      parentRoute: typeof ApiPortalTokenRoute
    }
    '/api/portal/$token/presence': {
      id: '/api/portal/$token/presence'
      path: '/presence'
      fullPath: '/api/portal/$token/presence'
      preLoaderRoute: typeof ApiPortalTokenPresenceRouteImport
      parentRoute: typeof ApiPortalTokenRoute
    }
    '/api/portal/$token/pay-proof': {
      id: '/api/portal/$token/pay-proof'
      path: '/pay-proof'
      fullPath: '/api/portal/$token/pay-proof'
      preLoaderRoute: typeof ApiPortalTokenPayProofRouteImport
      parentRoute: typeof ApiPortalTokenRoute
    }
    '/api/portal/$token/pay': {
      id: '/api/portal/$token/pay'
      path: '/pay'
      fullPath: '/api/portal/$token/pay'
      preLoaderRoute: typeof ApiPortalTokenPayRouteImport
      parentRoute: typeof ApiPortalTokenRoute
    }
    '/api/portal/$token/message': {
      id: '/api/portal/$token/message'
      path: '/message'
      fullPath: '/api/portal/$token/message'
      preLoaderRoute: typeof ApiPortalTokenMessageRouteImport
      parentRoute: typeof ApiPortalTokenRoute
    }
    '/api/portal/$token/file-delete': {
      id: '/api/portal/$token/file-delete'
      path: '/file-delete'
      fullPath: '/api/portal/$token/file-delete'
      preLoaderRoute: typeof ApiPortalTokenFileDeleteRouteImport
      parentRoute: typeof ApiPortalTokenRoute
    }
    '/api/portal/$token/file': {
      id: '/api/portal/$token/file'
      path: '/file'
      fullPath: '/api/portal/$token/file'
      preLoaderRoute: typeof ApiPortalTokenFileRouteImport
      parentRoute: typeof ApiPortalTokenRoute
    }
    '/api/portal/$token/confirm': {
      id: '/api/portal/$token/confirm'
      path: '/confirm'
      fullPath: '/api/portal/$token/confirm'
      preLoaderRoute: typeof ApiPortalTokenConfirmRouteImport
      parentRoute: typeof ApiPortalTokenRoute
    }
    '/api/portal/$token/approve': {
      id: '/api/portal/$token/approve'
      path: '/approve'
      fullPath: '/api/portal/$token/approve'
      preLoaderRoute: typeof ApiPortalTokenApproveRouteImport
      parentRoute: typeof ApiPortalTokenRoute
    }
    '/api/invoices/$id/verify': {
      id: '/api/invoices/$id/verify'
      path: '/verify'
      fullPath: '/api/invoices/$id/verify'
      preLoaderRoute: typeof ApiInvoicesIdVerifyRouteImport
      parentRoute: typeof ApiInvoicesIdRoute
    }
    '/api/invoices/$id/send': {
      id: '/api/invoices/$id/send'
      path: '/send'
      fullPath: '/api/invoices/$id/send'
      preLoaderRoute: typeof ApiInvoicesIdSendRouteImport
      parentRoute: typeof ApiInvoicesIdRoute
    }
    '/api/invoices/$id/pay': {
      id: '/api/invoices/$id/pay'
      path: '/pay'
      fullPath: '/api/invoices/$id/pay'
      preLoaderRoute: typeof ApiInvoicesIdPayRouteImport
      parentRoute: typeof ApiInvoicesIdRoute
    }
    '/api/clients/$id/whiteboard': {
      id: '/api/clients/$id/whiteboard'
      path: '/whiteboard'
      fullPath: '/api/clients/$id/whiteboard'
      preLoaderRoute: typeof ApiClientsIdWhiteboardRouteImport
      parentRoute: typeof ApiClientsIdRoute
    }
    '/api/clients/$id/timeline': {
      id: '/api/clients/$id/timeline'
      path: '/timeline'
      fullPath: '/api/clients/$id/timeline'
      preLoaderRoute: typeof ApiClientsIdTimelineRouteImport
      parentRoute: typeof ApiClientsIdRoute
    }
    '/api/clients/$id/send-welcome': {
      id: '/api/clients/$id/send-welcome'
      path: '/send-welcome'
      fullPath: '/api/clients/$id/send-welcome'
      preLoaderRoute: typeof ApiClientsIdSendWelcomeRouteImport
      parentRoute: typeof ApiClientsIdRoute
    }
    '/api/clients/$id/regenerate-portal': {
      id: '/api/clients/$id/regenerate-portal'
      path: '/regenerate-portal'
      fullPath: '/api/clients/$id/regenerate-portal'
      preLoaderRoute: typeof ApiClientsIdRegeneratePortalRouteImport
      parentRoute: typeof ApiClientsIdRoute
    }
    '/api/auth/2fa/verify': {
      id: '/api/auth/2fa/verify'
      path: '/api/auth/2fa/verify'
      fullPath: '/api/auth/2fa/verify'
      preLoaderRoute: typeof ApiAuth2faVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/2fa/validate': {
      id: '/api/auth/2fa/validate'
      path: '/api/auth/2fa/validate'
      fullPath: '/api/auth/2fa/validate'
      preLoaderRoute: typeof ApiAuth2faValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/2fa/setup': {
      id: '/api/auth/2fa/setup'
      path: '/api/auth/2fa/setup'
      fullPath: '/api/auth/2fa/setup'
      preLoaderRoute: typeof ApiAuth2faSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/2fa/disable': {
      id: '/api/auth/2fa/disable'
      path: '/api/auth/2fa/disable'
      fullPath: '/api/auth/2fa/disable'
      preLoaderRoute: typeof ApiAuth2faDisableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/conversations/$id': {
      id: '/api/ai/conversations/$id'
      path: '/$id'
      fullPath: '/api/ai/conversations/$id'
      preLoaderRoute: typeof ApiAiConversationsIdRouteImport
      parentRoute: typeof ApiAiConversationsRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardPortalRoute: typeof DashboardPortalRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardProposalsRoute: typeof DashboardProposalsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardPortalRoute: DashboardPortalRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardProposalsRoute: DashboardProposalsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiClientsIdRouteChildren {
  ApiClientsIdRegeneratePortalRoute: typeof ApiClientsIdRegeneratePortalRoute
  ApiClientsIdSendWelcomeRoute: typeof ApiClientsIdSendWelcomeRoute
  ApiClientsIdTimelineRoute: typeof ApiClientsIdTimelineRoute
  ApiClientsIdWhiteboardRoute: typeof ApiClientsIdWhiteboardRoute
}

const ApiClientsIdRouteChildren: ApiClientsIdRouteChildren = {
  ApiClientsIdRegeneratePortalRoute: ApiClientsIdRegeneratePortalRoute,
  ApiClientsIdSendWelcomeRoute: ApiClientsIdSendWelcomeRoute,
  ApiClientsIdTimelineRoute: ApiClientsIdTimelineRoute,
  ApiClientsIdWhiteboardRoute: ApiClientsIdWhiteboardRoute,
}

const ApiClientsIdRouteWithChildren = ApiClientsIdRoute._addFileChildren(
  ApiClientsIdRouteChildren,
)

interface ApiClientsRouteChildren {
  ApiClientsIdRoute: typeof ApiClientsIdRouteWithChildren
}

const ApiClientsRouteChildren: ApiClientsRouteChildren = {
  ApiClientsIdRoute: ApiClientsIdRouteWithChildren,
}

const ApiClientsRouteWithChildren = ApiClientsRoute._addFileChildren(
  ApiClientsRouteChildren,
)

interface ApiInvoicesIdRouteChildren {
  ApiInvoicesIdPayRoute: typeof ApiInvoicesIdPayRoute
  ApiInvoicesIdSendRoute: typeof ApiInvoicesIdSendRoute
  ApiInvoicesIdVerifyRoute: typeof ApiInvoicesIdVerifyRoute
}

const ApiInvoicesIdRouteChildren: ApiInvoicesIdRouteChildren = {
  ApiInvoicesIdPayRoute: ApiInvoicesIdPayRoute,
  ApiInvoicesIdSendRoute: ApiInvoicesIdSendRoute,
  ApiInvoicesIdVerifyRoute: ApiInvoicesIdVerifyRoute,
}

const ApiInvoicesIdRouteWithChildren = ApiInvoicesIdRoute._addFileChildren(
  ApiInvoicesIdRouteChildren,
)

interface ApiInvoicesRouteChildren {
  ApiInvoicesIdRoute: typeof ApiInvoicesIdRouteWithChildren
  ApiInvoicesProcessRecurringRoute: typeof ApiInvoicesProcessRecurringRoute
}

const ApiInvoicesRouteChildren: ApiInvoicesRouteChildren = {
  ApiInvoicesIdRoute: ApiInvoicesIdRouteWithChildren,
  ApiInvoicesProcessRecurringRoute: ApiInvoicesProcessRecurringRoute,
}

const ApiInvoicesRouteWithChildren = ApiInvoicesRoute._addFileChildren(
  ApiInvoicesRouteChildren,
)

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

interface ApiProposalsIdRouteChildren {
  ApiProposalsIdSendRoute: typeof ApiProposalsIdSendRoute
}

const ApiProposalsIdRouteChildren: ApiProposalsIdRouteChildren = {
  ApiProposalsIdSendRoute: ApiProposalsIdSendRoute,
}

const ApiProposalsIdRouteWithChildren = ApiProposalsIdRoute._addFileChildren(
  ApiProposalsIdRouteChildren,
)

interface ApiProposalsRouteChildren {
  ApiProposalsIdRoute: typeof ApiProposalsIdRouteWithChildren
}

const ApiProposalsRouteChildren: ApiProposalsRouteChildren = {
  ApiProposalsIdRoute: ApiProposalsIdRouteWithChildren,
}

const ApiProposalsRouteWithChildren = ApiProposalsRoute._addFileChildren(
  ApiProposalsRouteChildren,
)

interface ApiTasksRouteChildren {
  ApiTasksIdRoute: typeof ApiTasksIdRoute
  ApiTasksReorderRoute: typeof ApiTasksReorderRoute
}

const ApiTasksRouteChildren: ApiTasksRouteChildren = {
  ApiTasksIdRoute: ApiTasksIdRoute,
  ApiTasksReorderRoute: ApiTasksReorderRoute,
}

const ApiTasksRouteWithChildren = ApiTasksRoute._addFileChildren(
  ApiTasksRouteChildren,
)

interface ApiAiConversationsRouteChildren {
  ApiAiConversationsIdRoute: typeof ApiAiConversationsIdRoute
}

const ApiAiConversationsRouteChildren: ApiAiConversationsRouteChildren = {
  ApiAiConversationsIdRoute: ApiAiConversationsIdRoute,
}

const ApiAiConversationsRouteWithChildren =
  ApiAiConversationsRoute._addFileChildren(ApiAiConversationsRouteChildren)

interface ApiPortalTokenRouteChildren {
  ApiPortalTokenApproveRoute: typeof ApiPortalTokenApproveRoute
  ApiPortalTokenConfirmRoute: typeof ApiPortalTokenConfirmRoute
  ApiPortalTokenFileRoute: typeof ApiPortalTokenFileRoute
  ApiPortalTokenFileDeleteRoute: typeof ApiPortalTokenFileDeleteRoute
  ApiPortalTokenMessageRoute: typeof ApiPortalTokenMessageRoute
  ApiPortalTokenPayRoute: typeof ApiPortalTokenPayRoute
  ApiPortalTokenPayProofRoute: typeof ApiPortalTokenPayProofRoute
  ApiPortalTokenPresenceRoute: typeof ApiPortalTokenPresenceRoute
  ApiPortalTokenRevisionRoute: typeof ApiPortalTokenRevisionRoute
  ApiPortalTokenWhiteboardRoute: typeof ApiPortalTokenWhiteboardRoute
}

const ApiPortalTokenRouteChildren: ApiPortalTokenRouteChildren = {
  ApiPortalTokenApproveRoute: ApiPortalTokenApproveRoute,
  ApiPortalTokenConfirmRoute: ApiPortalTokenConfirmRoute,
  ApiPortalTokenFileRoute: ApiPortalTokenFileRoute,
  ApiPortalTokenFileDeleteRoute: ApiPortalTokenFileDeleteRoute,
  ApiPortalTokenMessageRoute: ApiPortalTokenMessageRoute,
  ApiPortalTokenPayRoute: ApiPortalTokenPayRoute,
  ApiPortalTokenPayProofRoute: ApiPortalTokenPayProofRoute,
  ApiPortalTokenPresenceRoute: ApiPortalTokenPresenceRoute,
  ApiPortalTokenRevisionRoute: ApiPortalTokenRevisionRoute,
  ApiPortalTokenWhiteboardRoute: ApiPortalTokenWhiteboardRoute,
}

const ApiPortalTokenRouteWithChildren = ApiPortalTokenRoute._addFileChildren(
  ApiPortalTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  CookieRoute: CookieRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RoadmapRoute: RoadmapRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiClientsRoute: ApiClientsRouteWithChildren,
  ApiInvoicesRoute: ApiInvoicesRouteWithChildren,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiPingRoute: ApiPingRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiProposalsRoute: ApiProposalsRouteWithChildren,
  ApiReferralsRoute: ApiReferralsRoute,
  ApiTasksRoute: ApiTasksRouteWithChildren,
  PortalClientIdRoute: PortalClientIdRoute,
  ApiAdminCampaignRoute: ApiAdminCampaignRoute,
  ApiAdminLeadsRoute: ApiAdminLeadsRoute,
  ApiAdminPromoCodesRoute: ApiAdminPromoCodesRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiConversationsRoute: ApiAiConversationsRouteWithChildren,
  ApiAiInlineRoute: ApiAiInlineRoute,
  ApiAuthValidateSignupRoute: ApiAuthValidateSignupRoute,
  ApiBillingCreateCheckoutRoute: ApiBillingCreateCheckoutRoute,
  ApiBillingCreatePortalRoute: ApiBillingCreatePortalRoute,
  ApiBillingInvoicesRoute: ApiBillingInvoicesRoute,
  ApiBillingSubscriptionRoute: ApiBillingSubscriptionRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiEmailWelcomeRoute: ApiEmailWelcomeRoute,
  ApiOnboardingCountsRoute: ApiOnboardingCountsRoute,
  ApiPortalTokenRoute: ApiPortalTokenRouteWithChildren,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiAuth2faDisableRoute: ApiAuth2faDisableRoute,
  ApiAuth2faSetupRoute: ApiAuth2faSetupRoute,
  ApiAuth2faValidateRoute: ApiAuth2faValidateRoute,
  ApiAuth2faVerifyRoute: ApiAuth2faVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
